apiVersion: v1
data:
  MYSQL_DATABASE: mydb
  MYSQL_PASSWORD: secret
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: admin
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-mysql--env
  name: mysql--env
