apiVersion: v1

#Element type.
kind: Pod

metadata:
  name: web
  labels:
    app: web


#Asosiated images. 
spec:
  containers:
    - name: front
      image: httpd:latest
      ports: 
        - containerPort: 80
         
    - name: back
      image: ubuntu:latest 
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10; done"]
