version: '3.4'
  #Load balancer 
  test-server:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./old-version:/var/www/old-version
      - ./new-version:/var/www/new-version
    networks:
      project:
        aliases:
          - proxy

#Local network
networks:
  project:
    driver: bridge
    ipam:
      driver: default



