version: "3.4"
services:
 #MySql db
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - "3306" 
    networks:
      project:
        aliases:
          - db

 #Wordpress server 
  wp:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./w_data/wordpress_data:/var/www/html
      - ./w_data/uploads:/var/www/wp-content/uploads
    expose:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: test
    networks:
      project:
        aliases:
          - wp

  #Wp accelerator          
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=500M  
    command: "-p default_keep=300"
    depends_on:
      - "wp"
    networks:
      project:
        aliases:
          - vn        
  
  #Db manager.
  pma:
    image: phpmyadmin
    #restart: always
    depends_on:
      - db
    ports:
      - "90:80"
    environment:
      - PMA_HOST=db  
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    networks:
      project:      
        aliases:
          - pma

#Local network.
networks:
  project:
    driver: bridge
    ipam:
      driver: default
