---
kind: Namespace
apiVersion: v1
metadata:
  name: empty

---
apiVersion:
apiVersion: v1
kind: Pod
metadata:
  name: empty
spec:
  containers:
  - name: c1
    namespace: empty
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - name: xchange
      mountPath: "/tmp/xchange"
      
 - name: c2
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - name: xchange
      mountPath: "/tmp/data"
volumes:
- name: xchange
  emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: empty
  namespace: empty
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: hello
