version: '3.4'
services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'ECUADOR/GUAYAQUIL'
    restart: unless-stopped
    command: '-u "lu;plastika" -s "compartido;/media;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      #- "445:445/tcp"
    volumes:
      - ../../shared:/media
