version: '3.4'
services:   
  web:
    image: nginx
    ports:
      - "80:80"
    networks:
       project:
         aliases:
           - web
  
  proxy:
    image: nginx
    ports:
     - "90:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/.htpasswd 
    depends_on:
      - web     
    networks:
      project:
        aliases:
          - proxy

networks:
  project:
    driver: bridge
    ipam:
      driver: default
        
